# Generated by Django 2.2.5 on 2020-01-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominio',
            name='nombre_dominio',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre_empresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='pregunta',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='nombre_seccion',
            field=models.CharField(max_length=80),
        ),
    ]
