# Generated by Django 2.2.5 on 2020-01-23 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200123_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='dominio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Dominio'),
            preserve_default=False,
        ),
    ]
