# Generated by Django 2.2.5 on 2020-01-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seccion_dominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion',
            name='nombre_seccion',
            field=models.CharField(max_length=120),
        ),
    ]
