# Generated by Django 2.2.5 on 2020-01-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200123_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='dominio',
        ),
    ]
