# Generated by Django 2.2.5 on 2020-01-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_pregunta_dominio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='seccion',
        ),
    ]
