# Generated by Django 2.2.5 on 2020-01-27 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200125_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Usuario'),
        ),
    ]
