# Generated by Django 2.2.5 on 2020-02-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_respuesta_fecha_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendacion', models.TextField()),
                ('nivel', models.CharField(max_length=10)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Dominio')),
            ],
        ),
    ]
