# Generated by Django 2.2.5 on 2020-02-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_recomendaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recomendaciones',
            new_name='Recomendacion',
        ),
    ]
