# Generated by Django 2.2.5 on 2020-02-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200212_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendacion',
            old_name='recomendacion',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='guia_referencia',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='nombre',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='objetivo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='referencia',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
