# Generated by Django 2.2.5 on 2020-02-24 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200221_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Dominio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Empresa')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Trabajador')),
            ],
        ),
    ]
