version: "3.0"

services:
  web:
    build: .
    image: newgap
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
